src/assets/Header.tsx
src/assets/MultiStepProgressBar.tsx
src/assets/VerificationBox.tsx
src/components/Footer.tsx
src/pages/SignUp/SignUp2Page.tsx

1. progressBar 와 Header 간 z-index 오류 해결
2. verificationBox 들 이미지 > div 컴포넌트로 전면 수정

fix: header, verificationBox, progressBar

---

src/App.tsx
src/assets/MultiStepProgressBar.tsx
src/assets/TextFieldBox.tsx
src/assets/dropdown/dropDown.tsx
src/components/Footer.tsx
src/pages/SignUp/SignUp2Page.tsx
src/pages/SignUp/SignUp3Page.tsx

최대한 디자인 그대로 작동할 수 있도록 구현해 보았는데, 클릭 위치에 따라서 클릭이 안 먹는다던지 하는 결점들이 있어서 수정이 더 필요할 거 같아요 + 추가적으로 아이디가 고려대학교 이메일이어야 한다는 작은 텍스트가 있는데 원래 옆에 체크 이미지가 있어야 하는데 이걸 못 넣어서 넣어야 할 거 같습니다
입력값이나 Textfield의 상태는 각 페이지의 컴포넌트에서 state를 이용하여 관리하도록 하였습니다.
optionlist는 일단 두 개만 만들어서 작동 확인만 해 보았습니다.

Signup page 2, Signup page 3 구현

---

src/assets/MultiStepProgressBar.tsx
src/components/Footer.tsx
src/pages/SignUp/SignUp2Page.tsx
src/pages/SignUp/SignUp5Page.tsx

이 부분 확인 부탁합니다
1. 화면이 길어져서 푸터 영역에 침범하는 경우가 생겨 Wrapper에  padding-bottom을 추가했는데 맞는지 모르겠습니다.
2. TextBox에 스크롤바가 계속 보이는데 사라지는 방법을 모르겠습니다
3. Asset에 있는 CheckButton을 수정하기 애매해서 코드 복사해서 약간의 수정을 거쳤는데 그냥 에셋에서 수정해도 되는지 확인 부탁합니다.
4. ArrowImage, CheckButton, Text 가 같은 높이에 위치하지 않은 것 같은데 잘 모르겠습니다.
부족한 부분 있으면 수정해서 다시 올리겠습니다

SignUp5Page 

---

src/assets/TextFieldBox.tsx
src/pages/SignUp/SignUp2Page.tsx
src/pages/SignUp/SignUp4Page.tsx
tsconfig.json

기존에 onClick으로 이벤트 처리하던 걸 onFocus로 바꿨습니다
이제 Placeholder 부분을 클릭해도 잘 작동하고, tab키로 textfield를 선택할 수 있도록 했습니다.

Textfield 수정 - 클릭 안 먹는 오류 해결 + tab키 작동

---

src/App.tsx
src/assets/Modal.tsx
src/assets/alert/AlertLarge.tsx
src/assets/alert/AlertSmall.tsx
src/components/Timer.tsx
src/pages/MainPage.tsx
src/pages/SignUp/SignUp1Page.tsx

회원가입페이지 1 타이머 작동되게 수정하였습니다.
페이지1의 모달창 작동되도록 수정하고 있습니다.

fix: timer

---

src/assets/TextFieldBox.tsx

password 입력창을 열면 password를 보이게 하는 눈 모양 아이콘을 추가하였습니다. 비밀번호가 보일 때와 안 보일 때의 아이콘이 다르도록 구현하였습니다. 
asset이 바뀌어서 꼭 반영해 주세요 ㅎㅎ

password 보이기 icon 추가

---

src/assets/LoginButton.tsx
src/assets/ScrollButton.tsx
src/pages/SignUp/SignUp5Page.tsx

아직 고칠 부분이 좀 있는데 미리 PR 올립니다... 나중에 수정되면 추가로 올리겠습니다.
수정한 부분
1. 스크롤바 커스텀했습니다.
2. Signupcomplet 페이지에서 로그인 페이지로 이동하는 버튼 생성하고 주소도 연결시켰습니다.
고쳐야 될 부분
1. 스크롤 바 마진 넣기
2. &::-moz-scrollbar, /* Firefox */ &::-ms-scrollbar /* Internet Explorer */ 여기에도 커스텀한 스크롤 바 적용하기
3. 스크롤 바 클릭 버튼 구간 다시 설정

fix: SignUp5Page and SignUp5Complete page

---

src/assets/ScrollButton.tsx
src/pages/SignUp/SignUp5Page.tsx

fix: ScrollButton and SignUp5Page

---

package-lock.json
package.json
src/assets/MyBoardChart.tsx
src/assets/buttons/InterestMajorButton.tsx
src/assets/buttons/InterestMajorEditButton.tsx
src/assets/buttons/MockApplication.tsx
src/pages/MyBoardPage.tsx

기능은 구현 안하고 껍데기만 만들었습니다.
완성본은 다시 올리겠습니다

myboard 일부 

---

src/App.tsx
src/assets/buttons/MockApplication.tsx
src/pages/MyBoardPage.tsx

feat: blur window, 모의지원 button asset for 4 states

---

src/assets/MyBoardChart.tsx
src/pages/MyBoard/MyBoardPage.tsx

myboardChart

---

public/design_image/fi_alert-circle.svg
src/assets/myboardpage/EditModalHeaderButton.tsx
src/assets/myboardpage/ImgCtrlButton.tsx
src/components/base/ModalLarge.tsx
src/pages/MyBoard/EditModals/EditDefaultModal.tsx
src/pages/MyBoard/EditModals/EditModal.tsx
src/pages/MyBoard/MyBoardPage.tsx
src/pages/MyBoard/SubmitModals/ApplicationModal.tsx
src/pages/SignUp/SignUp4Page.tsx

Edit Modal 거의 다 완성되었고, 아래 디테일한 부분만 약간 더 수정하면 됩니다.
```
/*
남은 개발
1. 프로필 사진 변경 - 버튼화
2. 인포 메세지 (헬프 메세지) 버튼화
3. 텍스트필드 입력값 유효성 조건 만족여부에 따른 아이콘 변화
*/
```
Application Modal 새로 시작했으며, 내일 마저 구현하겠습니다.

마이보드 모달창 수정

---

src/pages/ArchiveDetailPage.tsx
src/pages/MyBoard/MyBoardPage.tsx

feat: axios in myboard

---

package-lock.json
package.json
src/pages/MyBoard/MyBoardPage.tsx

feat: 희망 전공 최근 3학기 데이터 받기

---

src/components/landingpage/PassedDataCard.tsx
src/components/landingpage/RankingTable.tsx
src/pages/LandingPage.tsx

표, 합격정보 asset의 인터랙션까지 구현 완료하였습니다.

Figma 상 인터랙션 구현 완료

---

src/assets/myboardpage/HellpMessage.tsx

helpMessage

---

src/App.tsx
src/pages/MyBoard/MyBoardPage.tsx
src/pages/SignUp/SignUp1Page.tsx
src/pages/SignUp/SignUp3Page.tsx

마이보드 왼쪽 사이드 위치 수정, 
닉네임 7자 제한 수정
signup2 인덱스 수정

signup2, my board 수정

---

src/App.tsx
src/pages/SignUp/SignUp5Page.tsx

1. Header에 들어가는 login 여부 인자를 true -> isLogin으로 수정
2. join 코드의 phonenumber 받는 부분 삭제

로그인 만료 오류 해결

---

src/pages/MyBoard/SubmitModals/ApplicationModal.tsx

fix: 지원 시 1학년은 안되게

---

src/assets/myboardpage/MyBoardChart.tsx

급하게 수정해서 일반화 적용은 못했습니다.
이전: y축 interval: 0 - 50 -> 이후: y축 interval: 0 - 5
단과대별로 나뉘는 거라 50명은 너무 많아서 5명으로 줄였습니다

fix: y interval of plot graph

---

src/assets/myboardpage/MyBoardChart.tsx

fix: plot graph hover

---

src/assets/myboardpage/MyBoardChart.tsx

fix: x scale of plot graph 

---

src/App.tsx
src/assets/OldLogo.tsx
src/assets/OldTextFieldBox.tsx
src/assets/alert/LoginAlertLarge01.tsx
src/assets/alert/SignUpAlertLarge01.tsx
src/assets/alert/SignUpAlertLarge02.tsx
src/assets/alert/SignUpAlertLarge03.tsx
src/assets/buttons/LabelButton.tsx
src/assets/buttons/SubmitButton.tsx
src/assets/buttons/TextButton.tsx
src/assets/buttons/header/HeaderButton.tsx
src/components/base/Footer.tsx
src/components/base/Header.tsx
src/components/base/ModalLarge.tsx
src/components/signUp/modals/SignUpLarge1.tsx
src/components/signUp/modals/SignUpLarge2.tsx
src/components/signUp/modals/SignUpLarge3.tsx

Header 및 Footer의 반응형 개발을 완료하였습니다.

Feat/components/headerFooter: Header, Footer 반응형 개발

---

src/assets/GpaLineChart.tsx
src/assets/tabMenu/TabMenu01.tsx
src/assets/tabMenu/TabMenu04.tsx
src/components/Previous/Cards.tsx
src/components/Previous/Header.tsx
src/components/landing/FAQ.tsx
src/pages/archive/ArchiveDetailPage.tsx
src/pages/archive/PreviousPage.tsx
src/utils/Mappings.ts

합격자료 페이지 수정

---

src/assets/OldTextFieldBox.tsx
src/assets/SearchBar.tsx
src/assets/TextFieldBox.tsx
src/assets/alert/LoginAlertLarge01.tsx
src/assets/alert/SignUpAlertLarge02.tsx
src/assets/alert/SignUpAlertLarge03.tsx
src/components/base/Footer.tsx
src/components/base/Header.tsx
src/components/base/ModalLarge.tsx

반응형 기준점을 기존 768px에서 변경후 600px로 수정하였습니다.

반응형 maxwidth 600px 설정

---

src/Routes.tsx
src/assets/myboardpage/InterestMajorButton.tsx
src/assets/tabMenu/TabMenu02.tsx
src/assets/tabMenu/TabMenu05.tsx
src/assets/toolTips/ToolTip05.tsx
src/components/base/ModalLarge.tsx
src/components/myBoard/Graph/PieChart.tsx
src/components/myBoard/Graph/Scatter.tsx
src/components/myBoard/LiveApplicantStatus.tsx
src/components/myBoard/MajorBox.tsx
src/components/myBoard/ProfileBox.tsx
src/components/myBoard/QuartileIndicator.tsx
src/components/myBoard/ThreeYearIndicator.tsx
src/pages/myBoard/MyBoardPage.tsx

수정사항 반영 완료
모달 관련 변경사항도 추후에 올릴 예정

fix: myBoardPage

---

src/assets/SearchBar.tsx
src/assets/dropdown/DropDown02.tsx
src/assets/toolTips/ToolTip04.tsx
src/components/Previous/Cards.tsx
src/components/Previous/Header.tsx
src/pages/archive/ArchiveDetailPage.tsx
src/pages/archive/PreviousPage.tsx

searchBar container: width 100%로 수정
dorpdown02 정렬 일부 수정
이 외에 회의 때 논의됐던 수정 사항 반영 완료

fix: page/archive

---

public/designImage/carousel/CarouselKey1.svg
public/designImage/carousel/CarouselKey2.svg
public/designImage/carousel/CarouselKey3.svg
src/assets/carouselKey/CarouselKey.tsx
src/assets/pagination/Pagination.tsx
src/components/myBoard/Graph/Scatter.tsx

pagination 추가 
Carousel key 추가
myBoard 산점도 grid 수정

pagination / carousel key 에셋 추가

---

src/mobile/assets/progressIndicator/ProgressBar01.tsx
src/mobile/components/myboard/applyModal/NotSubmittedHeader.tsx
src/pages/mobileMyBoard/ApplyModal.tsx

fix apply modal and progressBar

fix apply modal and progressBar

---

src/pages/main/LandingPage.tsx

fix:profile box from landing page

---

src/components/landing/RankingTable.tsx
src/mobile/pages/LandingMobile.tsx

Table 삭제 (안보임) 원인에 대한 추가 Clarification 필요

hotfix: !isinRange case,  rankingTable disappear 문제에 따른 blur 임시 삭제

---

src/App.tsx
src/Routes.tsx
src/components/onboarding/Join1.tsx
src/components/sync/SyncPageWrapper.tsx
src/mobile/components/onboarding/Join1.tsx
src/mobile/pages/LoginPage.tsx
src/pages/login/OldLoginPage.tsx
src/pages/sync/SyncPage0.tsx
src/pages/sync/SyncPage1.tsx
src/pages/sync/SyncPage2.tsx

- web&mobile 온보딩 페이지 링크들
- web&mobile 로그인 페이지에 로고

Feature: web - 기존 쿠플라이 회원 고파스 연동 페이지

---

src/common/LastThreeSemesters.tsx
src/mappings/Mappings.ts

CurrentSemester 의 기준을 '6월까지' 1학기에서, '9월까지' 1학기로 변경.

9월 과도기 임시조치
